### ISSUE TITLE
<< on association gives Octopus::AssociationShardTracking::MismatchedShards

### ISSUE THREAD

**Issue by kaspernj** [thiagopradi/octopus#409]
Using Octopus on a followers environment can produce Octopus::AssociationShardTracking::MismatchedShards with using `<<`.

It would be nice with a way to disable this. Maybe it should always be disabled, if `shards.yml` defines `fully_replicated: true`? 

My followers all contain the same data as the master, and we use this as a way to lessen the load of the master database.

```ruby
class Academy < ActiveRecord::Base
  has_many :academy_users
  has_many :users
end
```

```ruby
class User < ActiveRecord::Base
  has_many :academy_users
  has_many :academies
end
```

```ruby
academy = Octopus.using(:follower_1) { Academy.find(1) }
user = User.find(1)

user.academies << academy #=> Octopus::AssociationShardTracking::MismatchedShards
```

I have solved it by doing this, but its a shame not being able to use the shortcut:
```ruby
user.academy_users.new(academy: academy)
```

**Comment by adomokos** [comment]
I bumped into the same thing today.

**Comment by adomokos** [comment]
Actually, check what shard names you are using. In the specs where I noticed this, I used strings and not symbols. There is a check [here](https://github.com/thiagopradi/octopus/blob/master/lib/octopus/association_shard_tracking.rb#L30), in my case it compared `"shard_3"` with `:shard_3` and threw the `MismatchedShards` error.

**Comment by thiagopradi** [comment]
Hi @adomokos / @kaspernj ,

I've fixed the error of comparing strings / symbols here: https://github.com/thiagopradi/octopus/commit/d9be235f2cc81ddf132f9d3869ea7f6dac857073 .

And, I agree that we shouldn't care about the `current_shard` when we are comparing objects in a fully replicated environment.  I'm going to try to work on it next week, but feel free to submit a patch to fix this :) .

Thiago

**Comment by lunaru** [comment]
Looks like this is still a problem in Octopus 0.9.2 on Rails 5.1 but when I downgraded to 0.9.1 this problem doesn't seem to exist.
